"Frontend GQL updates to connect to backend"
The-Sneaker-Society/sneaker-web pull request #21
Opened 2023-08-08 03:16 UTC by richardcolachagua

2023-08-09 22:30 UTC, AlanisYates requested changes

2023-08-09 22:30 UTC, AlanisYates commented on src/pages/MemberSettingsPage/ChangePassword/index.jsx
We don't store passwords on the backend it's all done through firebase look into how to send a pw reset email with the firebase docs

2023-08-09 22:30 UTC, AlanisYates commented on src/pages/MemberSettingsPage/MemberSettingsForm/index.jsx
> +      }
This looks Good

2023-08-09 22:30 UTC, AlanisYates commented on src/pages/MemberSettingsPage/MemberSettingsForm/index.jsx
> -      email: "",
Lets add in the initial value if they are already inputted that way they are shown to the user on first load

2023-08-17 23:38 UTC, richardcolachagua commented on src/pages/MemberSettingsPage/ChangePassword/index.jsx
handled this going to submit a new pr

2023-08-17 23:39 UTC, closed without merging