Stripe widget
The-Sneaker-Society/sneaker-web pull request #43
Opened 2024-03-14 00:36 UTC by richardcolachagua

Stripe Widget UI first draft. Ignore the commit from the contract status widget. I forgot to make a separate branch before committing.

2024-03-27 21:58 UTC, AlanisYates requested changes

2024-03-27 21:58 UTC, AlanisYates commented on src/components/ContractStatusWidget/ContractStatus.js
Remove from PR

2024-03-27 21:58 UTC, AlanisYates commented on src/components/ContractStatusWidget/ContractStatusWidget.jsx
Same remove from this PR

2024-03-27 23:55 UTC, richardcolachagua reviewed
Removed contract files

2024-04-09 00:46 UTC, richardcolachagua reviewed
removed files

2024-04-09 00:46 UTC, richardcolachagua commented on src/components/ContractStatusWidget/ContractStatusWidget.jsx
removed

2024-04-09 00:46 UTC, richardcolachagua commented on src/components/ContractStatusWidget/ContractStatus.js
removed

2024-04-13 12:09 UTC, AlanisYates requested changes
Remove the contract status files

2024-04-13 12:09 UTC, AlanisYates commented
Also pull in main

2024-04-18 00:06 UTC, richardcolachagua reviewed
"made contract status changes and pulled latest"

2024-06-20 23:19 UTC, closed without merging